---
# Adding common users to the system.
- name: Users | Create user accounts
  user:
    name: "{{ item.username }}"
    uid: "{{ item.uid }}"
  with_items: "{{ users }}"
  tags: 
    - users

- name: Users | Add authorized keys
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ lookup('file', '../../../inventories/users/keys/'+ item.username + '.key.pub' ) }}"
  with_items: "{{ users }}"
  tags: 
    - users

- name: Users | add sudoers
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/sermo_sudoers
    mode: 0440
  tags: 
    - users

- name: "Remove old user accounts"
  user:
    name: "{{ item }}"
    state: "absent"
    remove: yes
  with_items: "{{ remove_users }}"
  tags: 
    - users
